name: my_cep
description: Seach your CEP

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  flutter_bloc: ^8.0.1
  google_fonts: ^3.0.1
  dio: ^4.0.6
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  build_runner_core:


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
